// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOoIQ9AIvSVpAOZKi4-3J151U9JQhKFnQ',
    appId: '1:507580696837:web:6af34d07827e413314cf6c',
    messagingSenderId: '507580696837',
    projectId: 'test-project-2026-56d41',
    authDomain: 'test-project-2026-56d41.firebaseapp.com',
    storageBucket: 'test-project-2026-56d41.firebasestorage.app',
    measurementId: 'G-QSEKN5RDXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKvxOHvjsEpXJdCTs5FuG8R_TvMjfbxg',
    appId: '1:507580696837:android:8f095f173a2debf214cf6c',
    messagingSenderId: '507580696837',
    projectId: 'test-project-2026-56d41',
    storageBucket: 'test-project-2026-56d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXHr9jEM4LXQddm3o-sj8AObC1eyuIIs4',
    appId: '1:507580696837:ios:56a9099992a2b77614cf6c',
    messagingSenderId: '507580696837',
    projectId: 'test-project-2026-56d41',
    storageBucket: 'test-project-2026-56d41.firebasestorage.app',
    iosClientId: '507580696837-dl810gsdcoqm6p6qq7j37d1rmdo0gbd4.apps.googleusercontent.com',
    iosBundleId: 'com.sirikay.bonded',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXHr9jEM4LXQddm3o-sj8AObC1eyuIIs4',
    appId: '1:507580696837:ios:af878863d3ed7b3c14cf6c',
    messagingSenderId: '507580696837',
    projectId: 'test-project-2026-56d41',
    storageBucket: 'test-project-2026-56d41.firebasestorage.app',
    iosClientId: '507580696837-eedqb18g970b997dt2m0a65afimebj9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.bondedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOoIQ9AIvSVpAOZKi4-3J151U9JQhKFnQ',
    appId: '1:507580696837:web:8c465864883c397414cf6c',
    messagingSenderId: '507580696837',
    projectId: 'test-project-2026-56d41',
    authDomain: 'test-project-2026-56d41.firebaseapp.com',
    storageBucket: 'test-project-2026-56d41.firebasestorage.app',
    measurementId: 'G-7BBX95VH8P',
  );
}
